KnabCryptoExchange/KnabCryptoExchange/Models/CoinMarketCapConfig.cs
namespace KnabCryptoExchange.Models;

public class CoinMarketCapConfig
{
    public string ApiKey { get; set; }
    public string ApiUrl { get; set; }
}

KnabCryptoExchange/KnabCryptoExchange/Models/CryptoValue.cs
namespace KnabCryptoExchange.Models;

public class CryptoValue
{
    public required string Currency { get; set; }
    public double Price { get; set; }
}

KnabCryptoExchange/KnabCryptoExchange/Models/ErrorViewModel.cs
namespace KnabCryptoExchange.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KnabCryptoExchange/KnabCryptoExchange/Controllers/CryptoExchangeController.cs
using System.Diagnostics;
using System.Reflection.PortableExecutable;
using System.Threading.Tasks;
using KnabCryptoExchange.Models;
using KnabCryptoExchange.Service;
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Microsoft.AspNetCore.Mvc;

namespace KnabCryptoExchange.Controllers
{
    public class CryptoExchangeController : Controller
    {
        private readonly ILogger<CryptoExchangeController> _logger;
        private readonly ICryptoExchangeService cryptoExchangeService;

        public CryptoExchangeController(ILogger<CryptoExchangeController> logger, ICryptoExchangeService cryptoExchangeService)
        {
            _logger = logger;
            this.cryptoExchangeService = cryptoExchangeService;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Exchange(string cryptoCode)
        {
            if (ModelState.IsValid)
            {
                ViewData["CryptoCode"] = cryptoCode;

                var results = await cryptoExchangeService.Fetch(cryptoCode);

                return View("Display", results);
            }

            return View("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KnabCryptoExchange/KnabCryptoExchange/Controllers/HomeController.cs
using System.Diagnostics;
using System.Reflection.PortableExecutable;
using System.Threading.Tasks;
using KnabCryptoExchange.Models;
using KnabCryptoExchange.Service;
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Microsoft.AspNetCore.Mvc;

namespace KnabCryptoExchange.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICryptoExchangeService cryptoExchangeService;

        public HomeController(ILogger<HomeController> logger, ICryptoExchangeService cryptoExchangeService)
        {
            _logger = logger;
            this.cryptoExchangeService = cryptoExchangeService;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Exchange(string cryptoCode)
        {
            if (ModelState.IsValid)
            {
                ViewData["CryptoCode"] = cryptoCode;

                var results = await cryptoExchangeService.Fetch(cryptoCode);

                return View("Display", results);
            }

            return View("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KnabCryptoExchange/KnabCryptoExchange/Views/CryptoExchange/Display.cshtml
@{
    ViewData["Title"] = "Crypto Exchange";
}

@model List<CryptoValue>

@if (ViewData["CryptoCode"] != null)
{
    <div class="alert alert-success">
        Different Values for Crypto Code: @ViewData["CryptoCode"]
    </div>
}

<table border="1" class="bordered-table">
    <thead>
        <tr>
            <th>Currency</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var currency in Model)
        {
            <tr>
                <td>@currency.Currency</td>
                <td>@currency.Price.ToString("F2")</td>
            </tr>
        }
    </tbody>
</table>

KnabCryptoExchange/KnabCryptoExchange/Views/CryptoExchange/Index.cshtml
@{
    ViewData["Title"] = "Crypto Exchange";
}

<form asp-action="Exchange" method="post">
    <div class="form-group">
        <label for="inputValue">Enter a Crypto Currency Code:</label>
        <input type="text" id="cryptoCode" name="cryptoCode" placeholder="Enter a crypto currency code here, for ex: BTC, ETH" class="form-control" required />
    </div>
    <div></div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

KnabCryptoExchange/KnabCryptoExchange/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KnabCryptoViewer</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KnabCryptoViewer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KnabCryptoViewer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CryptoExchange" asp-action="Index">Crypto Exchange</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CryptoExchange" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - KnabCryptoViewer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>